### ISSUE TITLE
License agreement violation

### ISSUE THREAD

**Issue by ethindp** [khonsulabs/fmod-sys#2]
Placing the FMOD binaries within a version control system is probably a violation of the FMOD EULA in sec. 1.2. A good way of solving this would be just to assume default paths in build.rs (on windows) or to allow overriding with an environment variable that the user can set so that no FMOD-based code/binaries are needed in the repository itself. If I'm wrong about this, that's okay too, but the last time I asked FMOD about this they explicitly indicated that (at least) redistributing the installers/compressed archives was not legal or something along those lines.

**Comment by ecton** [comment]
I agree that locating them on the system would be a better approach. I'm currently not planning on using fmod in any of my projects, however, for various unrelated reasons, so this project is not being maintained. Your issue just prompted me to realize I should unpublish on crates.io and archive this project -- feel free to fork and run with it if you'd like to!
